version: "3.9"
services:
  db:
    image: postgres:16
    container_name: dental_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - dental_sql_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
volumes:
  dental_sql_data:
